name: NetFx

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout Code

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Restore NuGet Packages
      run: nuget restore BlockSpamCalls.sln

    - name: Build Web App
      run: msbuild BlockSpamCalls.sln /verbosity:minimal

    - name: Run Tests with VSTest
      run:  vstest.console.exe .\BlockSpamCalls.Test\bin\Debug\BlockSpamCalls.Test.dll
